"""2024-03_06_Add status column

Revision ID: 0bf19436ba08
Revises: fb4256a3df31
Create Date: 2024-03-06 02:18:00.241553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf19436ba08'
down_revision: Union[str, None] = 'fb4256a3df31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE refundticketstatusenum as ENUM('OPEN', 'CLOSED')")
    op.add_column(
        'refunds',
        column=sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='refundticketstatusenum'), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'status')
    # ### end Alembic commands ###
