"""Upgrade payment

Revision ID: 0fd3d9aa63b9
Revises: 0bf19436ba08
Create Date: 2024-03-07 09:20:00.689604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fd3d9aa63b9'
down_revision: Union[str, None] = '0bf19436ba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_external_payment_id_key', 'payments', type_='unique')
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='refundticketstatusenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='refundticketstatusenum'),
               nullable=False)
    op.create_unique_constraint('payments_external_payment_id_key', 'payments', ['external_payment_id'])
    # ### end Alembic commands ###
