"""2024-09-02_Add payment id

Revision ID: 252a4e9b8aae
Revises: 1583bbb42208
Create Date: 2024-02-29 10:14:12.403556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '252a4e9b8aae'
down_revision: Union[str, None] = '1583bbb42208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('actual_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'actual_payment_id')
    # ### end Alembic commands ###
