"""2024-03_09_Ad ondelete

Revision ID: 297a04e662e3
Revises: 19b28d1fa6cf
Create Date: 2024-03-10 02:10:54.356102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297a04e662e3'
down_revision: Union[str, None] = '19b28d1fa6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_subscription_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_subscription_id_fkey'), 'payments', 'subscriptions', ['subscription_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('refunds', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('refunds_subscription_id_fkey', 'refunds', type_='foreignkey')
    op.create_foreign_key(op.f('refunds_subscription_id_fkey'), 'refunds', 'subscriptions', ['subscription_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('refunds_subscription_id_fkey'), 'refunds', type_='foreignkey')
    op.create_foreign_key('refunds_subscription_id_fkey', 'refunds', 'subscriptions', ['subscription_id'], ['id'])
    op.alter_column('refunds', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('payments_subscription_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key('payments_subscription_id_fkey', 'payments', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
