"""Added refund models

Revision ID: 37e40302bea1
Revises: 408399798b12
Create Date: 2024-03-05 15:17:33.897274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37e40302bea1'
down_revision: Union[str, None] = '408399798b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_reasons',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refund_reasons_pkey'))
    )
    op.create_table('refunds ',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['refund_reasons.id'], name=op.f('refunds _reason_id_fkey')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('refunds _subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds _pkey'))
    )
    op.alter_column('prices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=True)
    op.drop_table('refunds ')
    op.drop_table('refund_reasons')
    # ### end Alembic commands ###
