"""2024-03_05_Remove external payment_type_id from paymetns

Revision ID: 505a6c4e1375
Revises: 408399798b12
Create Date: 2024-03-05 14:05:04.616290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '505a6c4e1375'
down_revision: Union[str, None] = '408399798b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'external_payment_type_id')
    op.alter_column('prices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'currency',
               existing_type=postgresql.ENUM('RUB', 'USD', 'EUR', name='currencyenum'),
               nullable=True)
    op.add_column('payments', sa.Column('external_payment_type_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
