"""2024-03_06_Add nullable for field

Revision ID: 7c986d3848f2
Revises: d8f415c2bc58
Create Date: 2024-03-06 00:21:46.766691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c986d3848f2'
down_revision: Union[str, None] = 'd8f415c2bc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
