"""2024-03_06_Change user id column type

Revision ID: ae7af795a9f6
Revises: 0bf19436ba08
Create Date: 2024-03-06 17:46:28.942462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ae7af795a9f6'
down_revision: Union[str, None] = '0bf19436ba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='refundticketstatusenum'),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'user_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='refundticketstatusenum'),
               nullable=False)
    # ### end Alembic commands ###
