"""2024-03_06_Change relations

Revision ID: d8f415c2bc58
Revises: 505a6c4e1375
Create Date: 2024-03-06 00:04:12.201872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f415c2bc58'
down_revision: Union[str, None] = '505a6c4e1375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('subscription_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('payments_subscription_id_fkey'), 'payments', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_constraint('subscriptions_payment_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('subscriptions_payment_id_fkey', 'subscriptions', 'payments', ['payment_id'], ['id'])
    op.drop_constraint(op.f('payments_subscription_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'subscription_id')
    # ### end Alembic commands ###
