"""2024-03_06_Fix table name

Revision ID: fb4256a3df31
Revises: 6a3e79453f29
Create Date: 2024-03-06 02:10:36.008851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fb4256a3df31'
down_revision: Union[str, None] = '6a3e79453f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['refund_reasons.id'], name=op.f('refunds_reason_id_fkey')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('refunds_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refunds_pkey'))
    )
    op.drop_table('refunds ')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds ',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"refunds _id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('reason_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('additional_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['refund_reasons.id'], name='refunds _reason_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='refunds _subscription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refunds _pkey')
    )
    op.drop_table('refunds')
    # ### end Alembic commands ###
