from datetime import datetime


test_data = {
    "features": [
        {
            "id": 1,
            "name": "First Feature",
            "description": "First Test Feature!",
            "available_entities": "[]",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 2,
            "name": "Second Feature",
            "description": "Second Test Feature!",
            "available_entities": "[]",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 3,
            "name": "Third Feature",
            "description": "Third Test Feature!",
            "available_entities": "[]",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
    ],
    "plans": [
        {
            "id": 1,
            "name": "First Plan",
            "description": "",
            "is_active": True,
            "is_recurring": True,
            "duration": 1,
            "duration_unit": "month",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 2,
            "name": "Second Plan",
            "description": "",
            "is_active": False,
            "is_recurring": True,
            "duration": 1,
            "duration_unit": "month",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 3,
            "name": "Third Plan",
            "description": "",
            "is_active": True,
            "is_recurring": False,
            "duration": 1,
            "duration_unit": "month",
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
    ],
    "payments": [
        {
            "id": 1,
            "payment_provider_id": 1,
            "payment_method": 'bank_card',
            "status": "created",
            "currency": "RUB",
            "amount": 100.00,
            "external_payment_id": None,
            "external_payment_type_id": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 2,
            "payment_provider_id": 2,
            "payment_method": {'bank_card'},
            "status": "succeeded",
            "currency": "RUB",
            "amount": 300.00,
            "external_payment_id": None,
            "external_payment_type_id": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 3,
            "payment_provider_id": 1,
            "payment_method": 'bank_card',
            "status": "cancelled",
            "currency": "RUB",
            "amount": 300.00,
            "external_payment_id": None,
            "external_payment_type_id": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
    ],
    "prices": [
        {
            "id": 1,
            "plan_id": 1,
            "currency": "RUB",
            "amount": 100.00,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 2,
            "plan_id": 2,
            "currency": "RUB",
            "amount": 200.00,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 3,
            "plan_id": 3,
            "currency": "RUB",
            "amount": 300.00,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
    ],
    "subscriptions": [
        {
            "id": 1,
            "plan_id": 1,
            "payment_provider_id": 1,
            "currency": "RUB",
            "payment_method": "bank_card",
            "user_id": "cc6e0b24-a46f-4c8e-beb0-b28479f3b203",
            "return_url": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 2,
            "plan_id": 1,
            "payment_provider_id": 1,
            "currency": "RUB",
            "payment_method": "bank_card",
            "user_id": "c849081f-9a99-4ff0-aa54-33118d2abaee",
            "return_url": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
        {
            "id": 3,
            "plan_id": 1,
            "payment_provider_id": 1,
            "currency": "RUB",
            "payment_method": "bank_card",
            "user_id": "c849081f-9a99-4ff0-aa54-33118d2abaee",
            "return_url": None,
            "created_at": datetime(2024, 1, 1),
            "updated_at": datetime(2024, 1, 1),
        },
    ],
    "payment_providers": [
        {"id": 1, "name": "Yookassa", "description": None, "is_active": True}
    ],
}
